export enum TokenType {
  SELECT = 'SELECT',
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  CREATE = 'CREATE',
  ALTER = 'ALTER',
  DROP = 'DROP',

  FROM = 'FROM',
  WHERE = 'WHERE',
  SET = 'SET',
  INTO = 'INTO',
  VALUES = 'VALUES',
  PRIMARY = 'PRIMARY',
  KEY = 'KEY',
  UNIQUE = 'UNIQUE',
  TIMESTAMP = 'TIMESTAMP',

  TABLE = 'TABLE',
  DATABASE = 'DATABASE',

  COMMA = 'COMMA',
  SEMI_COLON = 'SEMI_COLON',
  LPAREN_OPERATOR = 'LPAREN_OPERATOR',
  RPAREN_OPERATOR = 'RPAREN_OPERATOR',
  COMPARISON_OPERATOR = 'COMPARISON_OPERATOR',
  ASTERISK = '*',

  NUMBER_LITERAL = 'NUMBER_LITERAL',
  STRING_LITERAL = 'STRING_LITERAL',
  BOOLEAN_LITERAL = 'BOOLEAN_LITERAL',
  IDENTIFIER = 'IDENTIFIER',
  DATATYPE = 'DATATYPE',
}

export const KEYWORDS = new Set([
  TokenType.SELECT,
  TokenType.INSERT,
  TokenType.UPDATE,
  TokenType.DELETE,
  TokenType.CREATE,
  TokenType.ALTER,
  TokenType.DROP,
]);
